- $id: env
  type: object
  properties: {}
  required: []

- $id: public-config
  type: object
  properties: {}

- $id: config
  type: object
  properties:
    access:
      type: array
      items:
        type: object
        properties:
          host: { enum: [local, host, hostssl, hostnossl, hostgssenc, hostnogssenc] }

          database: { type: string }

          user: { type: string }

          address: { type: ["null", string] }

          auth-method: { enum: [trust, reject, scram-sha-256, md5, password, gss, sspi, ident, peer, ldap, radius, cert, pam, bsd] }

          auth-options: { type: ["null", string] }

        additionalProperties: false
        required: [host, database, user, address, auth-method, auth-options]

    replication:
      type: object
      properties:
        host: { type: string }
        port: { type: string, format: ip-port }
        username: { type: string }
        password: { type: string }
      additionalProperties: false
      required: [host, port, username, password]

    settings:
      type: ["null", object]

  additionalProperties: false
  required: [access]
