#!/usr/bin/env -S docker stack deploy --with-registry-auth postgresql -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml postgresql
#
# docker node update --label-add postgresql=primary `docker node inspect self --format "{{ .ID }}"`
# docker node update --label-add postgresql=sync `docker node inspect self --format "{{ .ID }}"`
# docker node update --label-add postgresql=async `docker node inspect self --format "{{ .ID }}"`
# docker node update --label-add postgresql=backup `docker node inspect self --format "{{ .ID }}"`

services:
  postgresql:
    image: ghcr.io/zerocluster/postgresql/16
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.postgresql == primary"

    command: --service=primary

    configs:
      - { source: env.yaml, target: /var/local/package/env.yaml }

    networks: [main]

    # ports:
    #   - { published: 5432, target: 5432 }

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: postgresql, target: /var/local/package/data }
      - { type: bind, source: /var/run/postgresql, target: /var/run/postgresql }

    build: .

  postgresql-sync:
    image: ghcr.io/zerocluster/postgresql/16
    depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 0 # must be equal to the replication.sync.numberOfStandbys in app config
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.postgresql == sync"

    command: --service=standby-sync

    configs:
      - { source: env.yaml, target: /var/local/package/env.yaml }

    networks: [main]

    # ports:
    #   - { published: 5433, target: 5432 }

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: postgresql, target: /var/local/package/data }
      - { type: bind, source: /var/run/postgresql, target: /var/run/postgresql }

  postgresql-async:
    image: ghcr.io/zerocluster/postgresql/16
    depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 0
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.postgresql == async"

    command: --service=standby-async

    configs:
      - { source: env.yaml, target: /var/local/package/env.yaml }

    networks: [main]

    # ports:
    #   - { published: 5434, target: 5432 }

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: postgresql, target: /var/local/package/data }
      - { type: bind, source: /var/run/postgresql, target: /var/run/postgresql }

  postgresql-backup:
    image: ghcr.io/zerocluster/postgresql/16
    depends_on: [postgresql]
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 0
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.postgresql == backup"

    command: --service=standby-backup

    configs:
      - { source: env.yaml, target: /var/local/package/env.yaml }

    networks: [main]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: postgresql, target: /var/local/package/data }
      - { type: bind, source: /var/run/postgresql, target: /var/run/postgresql }

configs:
  env.yaml: { file: env.yaml }

networks:
  main: { external: true }

volumes:
  postgresql: { name: postgresql }
