version: "3.9"

services:
  postgresql-15:
    image: ghcr.io/zerocluster/postgresql/15

    build:
      args:
        POSTGRESQL_VERSION: 16

  postgresql-16:
    depends_on: [node]
    image: ghcr.io/zerocluster/postgresql/16

    build:
      args:
        POSTGRESQL_VERSION: 16
