#!/usr/bin/env -S docker stack deploy --with-registry-auth pgsql -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml pgsql
# docker node update --label-add pgsql=true <NODE-NAME>

services:
  pgsql:
    image: zerocluster/pgsql-14
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.pgsql == true"

    # healthcheck:
    #   test: curl -f http://127.0.0.1/api/healthcheck || exit 1
    #   start_period: 60s
    #   interval: 15s
    #   timeout: 10s
    #   retries: 3

    # environment:
    #   NODE_ENV: development

    configs:
      - { source: env.yaml, target: /var/local/package/env.yaml }

    networks: [private]

    ports:
      - { published: 5432, target: 5432 }

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: pgsql, target: /var/lib/docker/volumes/pgsql/_data }
      - { type: bind, source: /var/run/postgresql, target: /var/run/postgresql }

    build:
      context: .

configs:
  env.yaml: { file: env.yaml }

networks:
  private: { external: true }

volumes:
  pgsql: { name: pgsql }

x-build:
  default_tag: latest
  auto_tags: [main, latest, next]
