#!/usr/bin/env -S docker stack deploy --with-registry-auth pgsql -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml pgsql
# PGSQL_POSTGRES_PASSWORD=1 docker stack deploy --with-registry-auth -c docker-stack.yaml pgsql
# docker node update --label-add pgsql=true <NODE-NAME>

services:
  pgsql:
    image: softvisio/pgsql
    hostname: pgsql

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.pgsql == true"

    environment:
      PGSQL_POSTGRES_PASSWORD: $PGSQL_POSTGRES_PASSWORD

    networks: [private]

    ports:
      - { published: 5432, target: 5432 }

    volumes:
      - { type: volume, source: pgsql, target: /var/lib/pgsql }

    init: true
    stop_grace_period: 5m
    shm_size: 1g

    build:
      labels:
        x-additional-image: registry.myworkforce.com/nginx/pgsql

networks:
  private: { external: true }

volumes:
  pgsql: { name: pgsql }

x-build:
  default_tag: latest
  # auto_tags: [main, devel, latest]
  # tags_mapping: { main: latest }
